# Generated by Django 4.2.7 on 2024-01-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='Volume',
            new_name='volume',
        ),
    ]
